# Generated by Django 4.2.16 on 2024-11-26 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer_name', models.CharField(max_length=200, null=True)),
                ('customer_places', models.CharField(max_length=200, null=True)),
                ('customer_price', models.FloatField(default=0.0)),
                ('customer_emailid', models.EmailField(blank=True, max_length=254, null=True)),
                ('customer_contactno', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
